[workspace]
[package]
version = "0.1.0"
name = "chess-script"
edition = "2021"

[dependencies]
sp1-sdk = { path = "../../../sdk" }
sp1-core = { path = "../../../core" }

[build-dependencies]
sp1-helper = { path = "../../../helper" }
