[package]
version = "0.1.0"
name = "zeth-example"
edition = "2021"

[dependencies]
bincode = "1.3.3"
hex-literal = "0.4.1"
succinct-core = { path = "../../core" }
zeth-lib = { git = "ssh://git@github.com/succinctlabs/zeth-private.git", branch = "chris/zeth-lib", default-features = false }
