[workspace]
[package]
name = "json-program"
version = "1.0.1"
edition = "2021"
publish = false

[dependencies]
sp1-zkvm = { path = "../../../zkvm/entrypoint" }
serde_json = "1.0.113"
serde = "1.0.197"
lib = { path = "../lib" }
