[package]
name = "patch-testing-script"
version = { workspace = true }
edition = { workspace = true }
publish = false

[dependencies]
sp1-core-executor = { workspace = true }
sp1-sdk = { workspace = true }

[build-dependencies]
sp1-build = { workspace = true }
