[package]
name = "sp1-precompiles"
version = "0.1.0"
edition = "2021"

[dependencies]
amcl = { package = "snowbridge-amcl", version = "1.0.2", default-features = false, features = [
    "bls381",
] }
anyhow = "1.0.83"
bincode = "1.3.3"
cfg-if = "1.0.0"
getrandom = { version = "0.2.14", features = ["custom"] }
hex = "0.4.3"
k256 = { version = "0.13.3", features = ["ecdsa", "std", "bits"] }
rand = "0.8.5"
serde = { version = "1.0.201", features = ["derive"] }
num = { version = "0.4.3" }

[features]
verify = []
