[workspace]
[package]
version = "0.1.0"
name = "ed25519-zkvm"
edition = "2021"

[dependencies]
succinct-zkvm = { path = "../../../zkvm" }
ed25519-dalek = { git = "https://github.com/dalek-cryptography/curve25519-dalek.git", rev = "0b45e00", version = "2.1.0" }
hex-literal = "0.4.1"

[patch.crates-io]
# Patch sha2 so we can use sha precompiles
sha2-v0-10-6 = { git = "https://github.com/succinctbot/RustCrypto-hashes.git", package = "sha2", branch = "main" }


