[package]
name = "sha"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
sp1-zkvm.workspace = true
sp1-sdk.workspace = true
sp1-core-executor.workspace = true

sha2 = { version = "0.9.9", package = "sha2" }
rand = "0.8.5"
sp1-test.workspace = true
sha3 = "=0.10.6"

[features]
prove = []
gpu = ["sp1-sdk/cuda"]


[build-dependencies]
sp1-build.workspace = true
