[package]
name = "sp1-recursion-program"
version = "0.0.0-test"
edition = "2021"
description = "SP1 is a performant, 100% open-source, contributor-friendly zkVM."
readme = "../../README.md"
license = "MIT OR Apache-2.0"

[dependencies]
p3-air = { workspace = true }
p3-field = { workspace = true }
p3-commit = { workspace = true }
p3-fri = { workspace = true }
p3-matrix = { workspace = true }
p3-maybe-rayon = { workspace = true }
p3-util = { workspace = true }
p3-symmetric = { workspace = true }
p3-challenger = { workspace = true }
p3-baby-bear = { workspace = true }
p3-dft = { workspace = true }
p3-merkle-tree = { workspace = true }
p3-poseidon2 = { workspace = true }
sp1-recursion-core = { path = "../core" }
sp1-recursion-compiler = { path = "../compiler" }
sp1-core = { path = "../../core" }
sp1-primitives = { path = "../../primitives" }
itertools = "0.13.0"
serde = { version = "1.0.201", features = ["derive"] }
rand = "0.8.5"
tracing = "0.1.40"
stacker = "0.1"

[features]
debug = ["sp1-core/debug"]