[package]
name = "fibonacci-script"
version = { workspace = true }
edition = { workspace = true }
default-run = "fibonacci-script"
publish = false

[dependencies]
itertools = "0.12.1"
sp1-sdk = { workspace = true }
sp1-prover = { workspace = true }
sha2 = "0.10.8"
bincode = "1.3.3"

[build-dependencies]
sp1-build = { workspace = true }

[[bin]]
name = "plonk_bn254"
path = "bin/plonk_bn254.rs"

[[bin]]
name = "compressed"
path = "bin/compressed.rs"

[[bin]]
name = "execute"
path = "bin/execute.rs"

[[bin]]
name = "fibonacci-script"
path = "src/main.rs"

[features]
cuda = ["sp1-sdk/cuda"]
