[package]
version = "0.1.0"
name = "fibonacci-script"
edition = "2021"
default-run = "fibonacci-script"

[dependencies]
itertools = "0.12.1"
sp1-sdk = { path = "../../../sdk" }
sha2 = "0.10.8"

[build-dependencies]
sp1-helper = { path = "../../../helper" }

[[bin]]
name = "groth16"
path = "bin/groth16.rs"

[[bin]]
name = "compressed"
path = "bin/compressed.rs"

[[bin]]
name = "execute"
path = "bin/execute.rs"

[[bin]]
name = "fibonacci-script"
path = "src/main.rs"