[package]
name = "sp1-recursion-gnark-ffi"
version = "0.1.0"
edition = "2021"

[dependencies]
p3-field = { workspace = true }
sp1-recursion-compiler = { path = "../compiler" }
serde = "1.0.198"
serde_json = "1.0.116"
tempfile = "3.10.1"
reqwest = { version = "0.11", features = ["json", "blocking"] }
rand = "0.8"
crossbeam = "0.8"
<<<<<<< HEAD
subtle-encoding = "0.5.1"
=======
log = "0.4.21"
>>>>>>> origin/main
