[package]
name = "sp1-zkvm"
version = "0.0.2-test.1"
edition = "2021"
description = "SP1 is a performant, 100% open-source, contributor-friendly zkVM."
readme = "../../README.md"
license = "MIT OR Apache-2.0"

[dependencies]
bincode = "1.3.3"
cfg-if = "1.0.0"
getrandom = { version = "0.2.14", features = ["custom"] }
once_cell = "1.19.0"
rand = "0.8.5"
serde = { version = "1.0.204", features = ["derive"] }
libm = { version = "0.2.8", optional = true }
sha2 = { version = "0.10.8" }
lazy_static = "1.5.0"

# optional
sp1-lib = { path = "../lib", optional = true, version = "0.0.2-test.1" }
sp1-primitives = { path = "../../primitives", optional = true, version = "0.0.2-test.1" }
p3-baby-bear = { workspace = true, optional = true }
p3-field = { workspace = true, optional = true }

[features]
default = ["libm", "lib"]
libm = ["dep:libm"]
lib = ["dep:sp1-lib"]
verify = [
  "dep:sp1-primitives",
  "dep:p3-baby-bear",
  "dep:p3-field",
  "sp1-lib/verify",
]
bn254 = ["sp1-lib/bn254"]
secp256k1 = ["sp1-lib/secp256k1"]
bls12381 = ["sp1-lib/bls12381"]
