[package]
name = "sp1-zkvm"
version = "0.1.0"
edition = "2021"

[dependencies]
sp1-precompiles = { path = "../precompiles" }
anyhow = "1.0.75"
bincode = "1.3.3"
cfg-if = "1.0.0"
getrandom = { version = "0.2.12", features = ["custom"] }
k256 = { version = "0.13.3", features = ["ecdsa", "std", "bits"] }
rand = "0.8.5"
serde = { version = "1.0.196", features = ["derive"] }
libm = { version = "0.2.8", optional = true }

[features]
default = ["libm"]
libm = ["dep:libm"]