[package]
name = "cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.79", features = ["backtrace"] }
cargo_metadata = "0.18.1"
clap = { version = "4.4.15", features = ["derive"] }
succinct-core = { path = "../core" }
reqwest = { version = "0.11.3", features = ["stream", "json"] }
futures-util = "0.3.14"
indicatif = "0.15.0"
tokio = { version = "1", features = ["full"] }
tar = "0.4"
flate2 = "1.0"
dirs = "4.0"
serde = { version = "1", features = ["derive"] }
downloader = { version = "0.2", default-features = false, features = ["rustls-tls"] }
