[package]
name = "ed_add"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
succinct-zkvm = { path = "../../zkvm" }
hex-literal = "0.4.1"
num = { version = "0.4.1", default-features = false }
