[package]
version = "0.1.0"
name = "rsp-script"
edition = "2021"

[dependencies]
alloy-primitives = "0.8.5"
bincode = "1.3.3"
clap = { version = "4.5.7", features = ["derive", "env"] }

# rsp
rsp-client-executor = { git = "https://github.com/succinctlabs/rsp/", rev = "3647076" }

# sp1
sp1-sdk = { path = "../../../crates/sdk" }

[build-dependencies]
sp1-build = { path = "../../../crates/build" }

[features]
default = []
cuda = ["sp1-sdk/cuda"]
