[package]
edition = "2021"
name = "sp1-recursion-core"
version = "0.1.0"

[dependencies]
p3-field = { workspace = true }
p3-baby-bear = { workspace = true }
p3-air = { workspace = true }
p3-matrix = { workspace = true }
p3-maybe-rayon = { workspace = true }
p3-poseidon2 = { workspace = true }
p3-symmetric = { workspace = true }
sp1-derive = { path = "../../derive" }
sp1-primitives = { path = "../../primitives" }
tracing = "0.1.40"
sp1-core = { path = "../../core" }
hashbrown = "0.14.5"
itertools = "0.12.1"
p3-bn254-fr = { workspace = true }
p3-merkle-tree = { workspace = true }
p3-commit = { workspace = true }
p3-dft = { workspace = true }
p3-challenger = { workspace = true }
p3-fri = { workspace = true }
zkhash = { git = "https://github.com/HorizenLabs/poseidon2" }
ff = { version = "0.13", features = ["derive", "derive_bits"] }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_with = "3.8.1"
backtrace = { version = "0.3.71", features = ["serde"] }
arrayref = "0.3.7"
static_assertions = "1.1.0"

[dev-dependencies]
rand = "0.8.5"
