[package]
name = "sp1-recursion-gnark-ffi"
description = "SP1 is a performant, 100% open-source, contributor-friendly zkVM."
readme = "../../../README.md"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }

[dependencies]
p3-field = { workspace = true }
p3-symmetric = { workspace = true }
p3-baby-bear = { workspace = true }
sp1-recursion-compiler = { workspace = true }
sp1-core-machine = { workspace = true }
sp1-stark = { workspace = true }
serde = "1.0.204"
serde_json = "1.0.121"
tempfile = "3.10.1"
log = "0.4.22"
num-bigint = "0.4.6"
cfg-if = "1.0"
bincode = "1.3.3"
anyhow = "1.0.86"
sha2 = "0.10.8"
hex = "0.4.3"

[build-dependencies]
bindgen = "0.70.1"
cc = "1.1"
cfg-if = "1.0"

[features]
native = []
