[package]
name = "inner-product_naive"
version = "1.0.0"
edition = "2021"
publish = false

[dependencies]
sp1-zkvm = { path = "../../../../crates/zkvm/entrypoint" }
sp1-derive = { path = "../../../../crates/derive" }
num-bigint = { workspace = true }
num = { version = "0.4.1" }
