[workspace]
[package]
version = "0.1.0"
name = "ecrecover"
edition = "2021"

[dependencies]
succinct-zkvm = { path = "../../zkvm" }
hex-literal = "0.4.1"
num = { version = "0.4.1", default-features = false }