[package]
name = "ssz-withdrawals-test"
version = "1.1.0"
edition = "2021"
publish = false

[dependencies]
sp1-zkvm = { path = "../../../zkvm/entrypoint" }
hex-literal = "0.4.1"
ssz_rs = { version = "0.9.0", features = ["serde"] }
hex = "0.4.3"
serde_with = { version = "3.4.0", features = ["hex"] }
serde = { workspace = true, features = ["derive"] }
alloy-primitives = "1.0"
sha2 = { git = "https://github.com/sp1-patches/RustCrypto-hashes.git", package = "sha2", branch = "patch-v0.9.8" }
