[workspace]
members = [
  "aggregation/script",
  "chess/script",
  "cycle-tracking/script",
  "fibonacci/script",
  "io/script",
  "is-prime/script",
  "json/lib",
  "json/script",
  "regex/script",
  "rsa/script",
  "ssz-withdrawals/script",
  "tendermint/script",
  "patch-testing/script",
]
resolver = "2"


[profile.release.build-override]
opt-level = 3