[workspace]
[package]
version = "0.1.0"
name = "rsa-program"
edition = "2021"

[dependencies]
sp1-zkvm = { path = "../../../zkvm/entrypoint" }
digest = "0.10.7"
rand = "0.8.5"
rsa = "0.6"                                      # Check for the latest version
sha2 = "0.9.8"                                   # Check for the latest version

[patch.crates-io]
# Patch sha2 so we can use sha precompiles
sha2 = { git = "https://github.com/succinctbot/RustCrypto-hashes.git", package = "sha2", branch = "v0.9.8" }
