[package]
name = "bn254-program"
version = "1.1.0"
edition = "2021"
publish = false

[dependencies]
sp1-zkvm = { path = "../../../crates/zkvm/entrypoint" }
bn = { git = "https://github.com/yuwen01/bn", package = "substrate-bn", branch = "yuwen/sp1-flag-0.6" }
# bn = { path = "../../../../bn", package = "substrate-bn"}
# bn = { git = "https://github.com/sp1-patches/bn", package = "substrate-bn", rev = "43d854d45b5727b1ff2b9f346d728e785bb8395c"}
# bn = { git = "https://github.com/sp1-patches/bn", package = "substrate-bn", branch = "patch-v0.6.0"}
rand = "0.8.5"
