[package]
name = "io-script"
version = { workspace = true }
edition = { workspace = true }
publish = false

[dependencies]
serde = { version = "1.0.196", features = ["derive"] }
sp1-sdk = { workspace = true }

[build-dependencies]
sp1-helper = { workspace = true }
