[package]
name = "io-program"
version = "1.1.0"
edition = "2021"
publish = false

[dependencies]
sp1-zkvm = { path = "../../../crates/zkvm/entrypoint" }
serde = { version = "1.0.195", features = ["derive"] }
