[package]
name = "sp1-recursion"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sp1-core = { path = "../../core" }
p3-baby-bear = { workspace = true }
p3-air = { workspace = true }
