[package]
name = "sp1-recursion-circuit"
version = "0.1.0"
edition = "2021"

[dependencies]
p3-air = { workspace = true }
p3-field = { workspace = true }
p3-commit = { workspace = true }
p3-fri = { workspace = true }
p3-matrix = { workspace = true }
p3-util = { workspace = true }
sp1-recursion-core = { path = "../core" }
sp1-core = { path = "../../core" }
itertools = "0.12.1"
serde = { version = "1.0.201", features = ["derive"] }
sp1-recursion-derive = { path = "../derive" }
sp1-recursion-compiler = { path = "../compiler" }
sp1-recursion-program = { path = "../program" }
p3-bn254-fr = { workspace = true }
p3-baby-bear = { workspace = true }
bincode = "1.3.3"

[dev-dependencies]
ff = { version = "0.13", features = ["derive", "derive_bits"] }
p3-challenger = { workspace = true }
p3-symmetric = { workspace = true }
p3-dft = { workspace = true }
p3-merkle-tree = { workspace = true }
p3-poseidon2 = { workspace = true }
zkhash = { git = "https://github.com/HorizenLabs/poseidon2" }
rand = "0.8.5"
sp1-recursion-gnark-ffi = { path = "../gnark-ffi" }
