[package]
name = "sha2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex-literal = "0.4.1"
sha2 = { git = "https://github.com/succinctbot/RustCrypto-hashes.git" }
succinct-zkvm = { path = "../../zkvm" }
hex = "0.4.3"
