[package]
name = "sp1-recursion-compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
p3-air = { workspace = true }
p3-field = { workspace = true }
p3-commit = { workspace = true }
p3-fri = { workspace = true }
p3-matrix = { workspace = true }
p3-symmetric = { workspace = true }
p3-util = { workspace = true }
sp1-recursion-core = { path = "../core" }
sp1-core = { path = "../../core" }
itertools = "0.12.1"
serde = { version = "1.0.201", features = ["derive"] }
sp1-recursion-derive = { path = "../derive" }
p3-bn254-fr = { workspace = true }
p3-baby-bear = { workspace = true }
p3-poseidon2 = { workspace = true }
backtrace = "0.3.71"
tracing = "0.1.40"

[dev-dependencies]
p3-challenger = { workspace = true }
p3-dft = { workspace = true }
p3-merkle-tree = { workspace = true }
rand = "0.8.5"
