[package]
name = "sp1-core-machine"
description = "SP1 is a performant, 100% open-source, contributor-friendly zkVM."
readme = "../../../README.md"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
links = "sp1-core-machine-sys"

[dependencies]
bincode = "1.3.3"
serde = { workspace = true, features = ["derive", "rc"] }
serde_json = { workspace = true }
itertools = { workspace = true }
log = "0.4.22"
num = { version = "0.4.3" }
p3-air = { workspace = true }
p3-baby-bear = { workspace = true }
p3-challenger = { workspace = true }
p3-field = { workspace = true }
p3-keccak-air = { workspace = true }
p3-matrix = { workspace = true }
p3-maybe-rayon = { workspace = true, features = ["parallel"] }
p3-uni-stark = { workspace = true }
p3-util = { workspace = true }
p3-symmetric = { workspace = true }
sp1-derive = { workspace = true }
sp1-primitives = { workspace = true }

rayon = "1.10.0"
rayon-scan = "0.1.1"

amcl = { package = "snowbridge-amcl", version = "1.0.2", default-features = false, features = [
  "bls381",
] }
cfg-if = "1.0.0"
generic-array = { version = "=1.1.0", features = ["alloc", "serde"] }
typenum = "1.17.0"
elliptic-curve = "0.13.8"
hex = "0.4.3"
k256 = { version = "0.13.3", features = ["expose-field"] }
p256 = { version = "0.13.2", features = ["expose-field"] }

num_cpus = "1.16.0"
size = "0.4.1"
tempfile = "3.10.1"
tracing = { workspace = true }
tracing-forest = { version = "0.1.6", features = ["ansi", "smallvec"] }
tracing-subscriber = { workspace = true, features = ["std", "env-filter"] }
strum_macros = "0.26"
strum = "0.26"
web-time = "1.1.0"
thiserror = "1.0.63"
rand = "0.8.5"
hashbrown = { workspace = true, features = ["serde", "inline-more"] }
static_assertions = "1.1.0"

sp1-stark = { workspace = true }
sp1-core-executor = { workspace = true }
sp1-curves = { workspace = true }
p3-poseidon2 = { workspace = true }

[dev-dependencies]
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
criterion = "0.5.1"
num = { version = "0.4.3", features = ["rand"] }
rand = "0.8.5"
sp1-zkvm = { workspace = true }
sp1-core-executor = { workspace = true }
test-artifacts = { workspace = true }

[build-dependencies]
sp1-stark = { workspace = true }
sp1-primitives = { workspace = true }
p3-baby-bear = { workspace = true }
cbindgen = "0.27.0"
cc = "1.1"
pathdiff = "0.2.1"
glob = "0.3.1"

[features]
default = ["sys"]
debug = []
bigint-rug = ["sp1-curves/bigint-rug"]
sys = []

[lib]
path = "src/lib.rs"
bench = false

[lints]
workspace = true
