[package]
name = "json-script"
version = { workspace = true }
edition = { workspace = true }
publish = false

[dependencies]
serde = "1.0.197"
serde_json = "1.0.114"
sp1-sdk = { workspace = true }
lib = { path = "../lib" }

[build-dependencies]
sp1-helper = { workspace = true }
