[package]
name = "sp1-sdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.12"
prost-types = "0.12"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
twirp = { git = "https://github.com/github/twirp-rs.git" }
async-trait = "0.1.77"
reqwest-middleware = "0.2.4"
reqwest = { version = "0.11.25", features = ["rustls-tls", "trust-dns"] }
anyhow = "1.0.80"
sp1-core = { path = "../core" }
futures = "0.3.30"
bincode = "1.3.3"
tokio = { version = "1.36.0", features = ["full"] }
p3-matrix = { workspace = true }
p3-commit = { workspace = true }
p3-field = { workspace = true }
indicatif = "0.17.8"
tracing = "0.1.40"
hex = "0.4.3"
log = "0.4.21"
axum = "=0.7.4"
alloy = { git = "https://github.com/alloy-rs/alloy", rev = "bfd0fda", features = [
    "contract",
    "signer-wallet",
] }
dotenv = "0.15.0"
sha2 = "0.10.8"

[features]
neon = ["sp1-core/neon"]
