[workspace]
[package]
version = "0.1.0"
name = "ssz-withdrawals-zkvm"
edition = "2021"
build = "build.rs"

[dependencies]
succinct-zkvm = { path = "../../zkvm" }
hex-literal = "0.4.1"
sha2 = "0.9.8"
ssz_rs = { version = "0.9.0", features = ["serde"] }
serde_json = "1.0.111"
hex = "0.4.3"
serde_with = { version = "3.4.0", features = ["hex"] }
serde = { version = "1.0.195", features = ["derive"] }
alloy-primitives = "0.6.0"