name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - "**"
    paths:
      - "core/**"
      - "recursion/**"
      - "sdk/**"
      - "examples/fibonacci-io/**"
      - ".github/workflows/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test core, recursion-compiler, recursion-program
    runs-on: warp-ubuntu-latest-arm64-16x
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup CI
        uses: ./.github/actions/setup
        with:
          pull_token: ${{ secrets.PULL_TOKEN }}

      - name: Run fibonacci-io example
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --release --manifest-path examples/fibonacci-io/script/Cargo.toml
        env:
          RUSTFLAGS: -Copt-level=3 -Cdebug-assertions -Coverflow-checks=y -Cdebuginfo=0
          RUST_LOG: 1
          RUST_BACKTRACE: 1
          CARGO_INCREMENTAL: 1

      - name: Run cargo test on sp1-core
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p sp1-core --release
        env:
          RUSTFLAGS: -Copt-level=3 -Cdebug-assertions -Coverflow-checks=y -Cdebuginfo=0
          RUST_LOG: 1
          RUST_BACKTRACE: 1
          CARGO_INCREMENTAL: 1

      - name: Run cargo test on sp1-recursion-compiler
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p sp1-recursion-compiler --release
        env:
          RUSTFLAGS: -Copt-level=3 -Cdebug-assertions -Coverflow-checks=y -Cdebuginfo=0
          RUST_LOG: 1
          RUST_BACKTRACE: 1
          CARGO_INCREMENTAL: 1

      - name: Run cargo test on sp1-recursion-program
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p sp1-recursion-program --release
        env:
          RUSTFLAGS: -Copt-level=3 -Cdebug-assertions -Coverflow-checks=y -Cdebuginfo=0
          RUST_LOG: 1
          RUST_BACKTRACE: 1
          CARGO_INCREMENTAL: 1

      - name: Run cargo test with no default features
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p sp1-core --profile fast --no-default-features --features debug -- cpu::trace::tests::generate_trace
        env:
          RUSTFLAGS: -Copt-level=3 -Cdebug-assertions -Coverflow-checks=y -Cdebuginfo=0
          RUST_LOG: 1
          RUST_BACKTRACE: 1
          CARGO_INCREMENTAL: 1

      - name: Run cargo test on sp1-recursion-circuit
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p sp1-recursion-circuit --release
        env:
          RUSTFLAGS: -Copt-level=3 -Cdebug-assertions -Coverflow-checks=y -Cdebuginfo=0
          RUST_LOG: 1
          RUST_BACKTRACE: 1
          CARGO_INCREMENTAL: 1

  test-recursion-circuit:
    name: Test recursion-circuit
    runs-on: warp-ubuntu-latest-arm64-16x
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup CI
        uses: ./.github/actions/setup
        with:
          pull_token: ${{ secrets.PULL_TOKEN }}

      - name: Run cargo test on sp1-recursion-circuit
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p sp1-recursion-circuit --release
        env:
          RUSTFLAGS: -Copt-level=3 -Cdebug-assertions -Coverflow-checks=y -Cdebuginfo=0
          RUST_LOG: 1
          RUST_BACKTRACE: 1

  lints:
    name: Formatting & Clippy
    runs-on: warp-ubuntu-latest-arm64-16x
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup CI
        uses: ./.github/actions/setup
        with:
          pull_token: ${{ secrets.PULL_TOKEN }}

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
        env:
          CARGO_INCREMENTAL: 1

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features --all-targets -- -D warnings -A incomplete-features
        env:
          CARGO_INCREMENTAL: 1
